remote_theme: thelehhman/plainwhite-jekyll

plainwhite:
  name: Sarbajit Chatterjee
  tagline: Developer at heart 
  date_format: "%b %-d, %Y"

  social_links:
    twitter: sarbajitc
    github:  sarbajitc
    linkedIn: in/sarbajit-chatterjee-b8a75010 # format: locale/username
    
