remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  name: Sarbajit Chatterjee
  tagline: Developer at heart 
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: false # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/portfolio.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    - home
    - page
    - post

  social_links:
    twitter: sarbajitc
    github:  sarbajitc
    linkedIn: in/sarbajit-chatterjee-b8a75010 # format: locale/username
